# Docker Compose configuration for TimeWarp Git
# Uncomment and configure for deployment

# version: '3.8'
# 
# services:
#   backend:
#     build: ./backend
#     ports:
#       - "8000:8000"
#     environment:
#       - DATABASE_URL=postgresql://postgres:password@db:5432/timewarp
#     depends_on:
#       - db
#     volumes:
#       - ./repos:/app/repos
# 
#   frontend:
#     build: ./frontend
#     ports:
#       - "3000:3000"
#     depends_on:
#       - backend
# 
#   db:
#     image: postgres:15
#     environment:
#       - POSTGRES_DB=timewarp
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=password
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"
# 
# volumes:
#   postgres_data: 